### ISSUE TITLE
DAPLINK_C6T6 的issues没开，我在这问吧

### ISSUE THREAD

**Issue by alanfans** [zhenruyan/WSL-libre-linux-kernel#4]
DAPLINK_C6T6编译出来55K,  stm32f103c6t6的flash只有32K,怎么放进去的？我刷进去后能识别，RST也能用，但是swd没法用

**Comment by zhenruyan** [comment]
> DAPLINK_C6T6编译出来55K, stm32f103c6t6的flash只有32K,怎么放进去的？我刷进去后能识别，RST也能用，但是swd没法用

我也不专业，我编译出来用另一个daplink烧进去 然后成功了（可以正常swd其他的stm32f103c6t6） hahah   我晚上回去再编译一下试试 看看结果一致不

**Comment by alanfans** [comment]
> > DAPLINK_C6T6编译出来55K, stm32f103c6t6的flash只有32K,怎么放进去的？我刷进去后能识别，RST也能用，但是swd没法用
> 
> 我也不专业，我编译出来用另一个daplink烧进去 然后成功了（可以正常swd其他的stm32f103c6t6） hahah 我晚上回去再编译一下试试 看看结果一致不

问题不大，已经可以用了，只是这个是daplink V1 现在在研究V2怎么弄
我看这大佬https://github.com/devanlai/dap42好像用的不是hal库，这个编译出来好小
